from hyper_config import *

import os
print("Dataset Loading...")
os.chdir('reproduction_scripts/scripts')
os.system('python load_targeted_data.py')
print("Dataset Loaded")

print("Survival analysis models")
print("Training...")
print("Baseline")
print("Cox-PH model")
os.chdir('baseline/coxph')
os.system('python main_grid.py')
print("RSF model")
os.chdir('../rf')
os.system('python main_grid.py')
print("2 layer fully connected network")
os.chdir('../../2layer/no_pathway')
os.system('python main.py')
print("2 layer pathway-informed network")
os.chdir('../pathway')
os.system('python main.py')
print("3 layer fully connected network")
os.chdir('../../3layer/no_pathway')
os.system('python main.py')
print("3 layer pathway-informed network")
os.chdir('../pathway')
os.system('python main.py')
print("4 layer fully connected network")
os.chdir('../../4layer/no_pathway')
os.system('python main.py')
print("4 layer pathway-informed network")
os.chdir('../pathway')
os.system('python main.py')
print("Training Finished")

print("Pathological classification models")
print("Training...")
print("2 layer fully connected network")
os.chdir('../../../tests/scripts/test5/2layer/no_pathway/')
os.system('python main.py')
print("2 layer pathway-informed network")
os.chdir('../pathway')
os.system('python main.py')
print("3 layer fully connected network")
os.chdir('../../3layer/no_pathway')
os.system('python main.py')
print("3 layer pathway-informed network")
os.chdir('../pathway')
os.system('python main.py')
print("4 layer fully connected network")
os.chdir('../../4layer/no_pathway')
os.system('python main.py')
print("4 layer pathway-informed network")
os.chdir('../pathway')
os.system('python main.py')
print("Training Finished")

print("Multitask models")
print("Training...")
print("2 layer fully connected network")
os.chdir('../../../test7/2layer/pathway/')
os.system('python main.py')
print("3 layer fully connected network")
os.chdir('../../3layer/pathway')
os.system('python main.py')
print("4 layer fully connected network")
os.chdir('../../4layer/pathway')
os.system('python main.py')
print("Training Finished")

print("All models trained")

print("Ablation study 1")
print("Training...")
print("2 layer fully connected network")
os.chdir('../../../test1/2layer/no_pathway/')
os.system('python main.py')
print("3 layer fully connected network")
os.chdir('../../3layer/no_pathway')
os.system('python main.py')
print("4 layer fully connected network")
os.chdir('../../4layer/no_pathway')
os.system('python main.py')
print("Training Finished")

print("Ablation study 2")
print("Training...")
print("2 layer randomly connected network")
os.chdir('../../../test2/2layer/no_pathway/')
os.system('python main.py')
print("3 layer randomly connected network")
os.chdir('../../3layer/no_pathway')
os.system('python main.py')
print("4 layer randomly connected network")
os.chdir('../../4layer/no_pathway')
os.system('python main.py')
print("Training Finished")

print("All training finished")


print("Results:")
os.chdir('../../../../../logs/')
os.system('python analysis.py')
print("Results printed")
print("Boxplots:")
os.system('python boxplot.py')
print("Figure 1 saved")

os.system('python boxplot2.py')
print("Figure 2 saved")
os.system('python boxplot3.py')
print("Figure 3 saved")

print("Shape analysis:")
os.system("../shap_analysis")
os.system("python shap_metabolites.py")
os.system("python shap_pathways.py")
print("Shap analysis finished")
print("Figure 4 saved")

print("All done")







